version: '3.8'

services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings

  # Note que o SQLite não precisa de um serviço separado.
  # O banco de dados será gerenciado como um arquivo dentro do contêiner.

volumes:
  # Define um volume persistente para o banco de dados SQLite
  sqlite_data:
